name: GitHub Actions Test
run-name: Deployment Action Triggered (${{ github.run_id }}) 🚀
on: [push]
jobs:
    explore-actions:
        runs-on: ubuntu-latest
        steps:
            - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
            - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
            - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
            - name: Check out repository code
              uses: actions/checkout@v4
            - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
            - name: Install Zola
              run: |
                sudo snap install zola --edge
            - name: Build Zola Application
              run: |
                zola build
                echo "Files in build directory"
                ls ${{ github.workspace}}/public
            - name: SSH Connection and File Transfer
              env:
                SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
                REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
                REMOTE_USER: ${{ secrets.REMOTE_USER }}
                REMOTE_PASS: ${{ secrets.REMOTE_PASS }}
              run: |
                echo "Connecting with password authentication"
                sudo apt-get install -y sshpass
                SSH_CMD="sshpass -p $REMOTE_PASS ssh -o StrictHostKeyChecking=no"
                SCP_CMD="sshpass -p $REMOTE_PASS scp"
                
                $SSH_CMD $REMOTE_USER@$REMOTE_HOST "rm -rf /var/www/html/*"
                $SCP_CMD -r ${{ github.workspace }}/public/* $REMOTE_USER@$REMOTE_HOST:/var/www/html/
                
            - name: Job Status
              run: echo "🍏 This job's status is ${{ job.status }}."